[metadata]
name = "stress"

[global]
plan = "graphsync"
case = "stress"
total_instances = 2
builder = "docker:go"
runner = "local:docker"

[global.run.test_params]
sizes      = '["256KB", "1MB", "4MB", "32MB", "128MB"]'
latencies = '["50ms", "100ms"]'
bandwidths = '["32MiB", "4MiB", "1MiB"]'
concurrency = "3"
chunk_size = "20"
links_per_level = "1024"
raw_leaves = "true"
disk_store = "true"

[[groups]]
id = "providers"
instances = { count = 1 }

[[groups]]
id = "requestors"
instances = { count = 1 }